language: node_js
node_js:
    - "4"
    - "5"
    - "6"
branches:
  except:
      - /^v[0-9]/
before_install:
    - sudo apt-get update -y -qq
    - sudo apt-get install -y libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
    - npm install -g npm
before_script:
    - npm install -g grunt-cli
