name: Test or Release

on:
  - push
  - pull_request

jobs:
  test-or-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
        registry-url: 'https://registry.npmjs.org'
    - name: Test
      run: |
        npm ci
        npm test
        npm run post_coverage
    - name: Publish
      uses: cycjimmy/semantic-release-action@v2
      with:
        semantic_version: 18
        branches: master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
